# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  votingApp: 
    spec:
      replicas: 2
    image:
      name: voting-app
      repository: lukmanadeokun31/voting-service
      tag: latest
      imagePullPolicy: IfNotPresent
      ports:
        containerPort: 8083

    service:
      type: ClusterIP
      port: 8083
      targetPort: 8083
    
    serviceAccount:
      create: true
  
  

