---
- name: Install Helm and deploy kube-prometheus-stack
  hosts: monitoring
  become: false

  tasks:
    - name: Install Helm if not present
      include_role:
        name: helm

    - name: Add Prometheus Community Helm repo
      command: >
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      args:
        creates: ~/.cache/helm/repository/prometheus-community-index.yaml

    - name: Update Helm repositories
      command: helm repo update

    - name: Wait for Kubernetes API to be reachable
      command: kubectl version # to prevent cluster check use `kubectl version --client`
      register: result
      retries: 10
      delay: 15
      until: result.rc == 0


    - name: Create monitoring namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: monitoring
        state: present

    - name: Install kube-prometheus-stack via Helm
      kubernetes.core.helm:
        name: kube-prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: false
        values: "{{ lookup('file', 'values/kube-prometheus-values.yaml') | from_yaml }}"
        state: present 
