apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app
  labels:
    name: demo-result-app
    app: demo-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: results-app
  template:
    metadata:
      labels:
        app: results-app
    spec:
      containers:
        - name: results-app
          image: "malik0x/result-app:2.1"
          ports:
            - containerPort: 8085
          env:
            - name: VOTING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: VOTING_SERVICE_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
