apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
        - name: worker-app
          image: lukmanadeokun31/worker-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "Omowunmi28"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_DB_NEW
              value: "votingdb"
            - name: REDIS_ADDR
              value: "redis:6379"
