apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  {{- with .Values.backend.postgres.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "postgres.labels" . | nindent 4 }}
