apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- with .Values.backend.secret.data }}
  POSTGRES_USER: {{ .POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .POSTGRES_PASSWORD }} 
  {{- end }}  