apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  {{- with .Values.backend.redis.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  selector:
    {{- include "redis.labels" . | nindent 4 }}
